#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DATA_FILE = path.join(ROOT, 'data', 'expenses.json');
const EXPORTS_DIR = path.join(ROOT, 'exports');

const args = process.argv.slice(2);
const monthArg = args.find(a => a.startsWith('--month='));
const targetMonth = monthArg
  ? monthArg.replace(/^--month=/, '').trim()
  : new Date().toISOString().slice(0, 7);

// ── Helpers ───────────────────────────────────────────────────────────────────

const fmt$ = n =>
  '$' + Math.abs(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function escHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ── Report Builder ────────────────────────────────────────────────────────────

function buildReport(data, month) {
  const txs = data.transactions.filter(t => t.date.startsWith(month));
  const expenses = txs.filter(t => t.amount < 0);
  const incomeItems = txs.filter(t => t.amount >= 0);

  const categoryTotals = {};
  for (const t of expenses) {
    categoryTotals[t.category] = (categoryTotals[t.category] || 0) + Math.abs(t.amount);
  }

  const grandTotal = Object.values(categoryTotals).reduce((a, b) => a + b, 0);
  const totalIncome = incomeItems.reduce((a, t) => a + t.amount, 0);
  const topExpenses = [...expenses].sort((a, b) => a.amount - b.amount).slice(0, 5);

  return { month, txs, categoryTotals, grandTotal, topExpenses, totalIncome };
}

// ── Markdown Generator ────────────────────────────────────────────────────────

function generateMarkdown({ month, txs, categoryTotals, grandTotal, topExpenses, totalIncome }) {
  const sorted = Object.entries(categoryTotals).sort((a, b) => b[1] - a[1]);

  let md = `# Expense Report — ${month}\n`;
  md += `*Generated ${new Date().toISOString().slice(0, 10)} · ${txs.length} transactions*\n\n---\n\n`;

  md += `## Spending by Category\n\n`;
  md += `| Category | Amount | Share |\n|---|---|---|\n`;
  for (const [cat, total] of sorted) {
    const pct = grandTotal > 0 ? ((total / grandTotal) * 100).toFixed(1) : '0.0';
    md += `| ${cat} | ${fmt$(total)} | ${pct}% |\n`;
  }
  md += `| **Total Expenses** | **${fmt$(grandTotal)}** | 100% |\n`;
  if (totalIncome > 0) md += `| *Income / Credits* | *${fmt$(totalIncome)}* | — |\n`;

  md += `\n---\n\n## Top 5 Individual Expenses\n\n`;
  if (topExpenses.length) {
    md += `| Date | Description | Amount | Category |\n|---|---|---|---|\n`;
    for (const t of topExpenses) {
      md += `| ${t.date} | ${t.description.replace(/\|/g, '-')} | ${fmt$(t.amount)} | ${t.category} |\n`;
    }
  } else {
    md += '*No expenses recorded for this month.*\n';
  }

  md += `\n---\n*Generated by scripts/expense-report.js · Source: data/expenses.json*\n`;
  return md;
}

// ── HTML Generator ────────────────────────────────────────────────────────────

function generateHTML({ month, txs, categoryTotals, grandTotal, topExpenses, totalIncome }) {
  const sorted = Object.entries(categoryTotals).sort((a, b) => b[1] - a[1]);

  const categoryRows = sorted.map(([cat, total]) => {
    const pct = grandTotal > 0 ? ((total / grandTotal) * 100).toFixed(1) : '0.0';
    const barWidth = grandTotal > 0 ? ((total / grandTotal) * 100).toFixed(1) : 0;
    return `
      <tr>
        <td>${escHtml(cat)}</td>
        <td>${fmt$(total)}</td>
        <td>
          <div style="display:flex;align-items:center;gap:8px">
            <div style="background:#0f3460;height:8px;border-radius:4px;width:${barWidth}%;min-width:2px;max-width:120px"></div>
            <span>${pct}%</span>
          </div>
        </td>
      </tr>`;
  }).join('');

  const topRows = topExpenses.map(t => `
    <tr>
      <td>${t.date}</td>
      <td>${escHtml(t.description)}</td>
      <td>${fmt$(t.amount)}</td>
      <td><span class="badge">${escHtml(t.category)}</span></td>
    </tr>`).join('');

  const incomeRow = totalIncome > 0
    ? `<tr class="income-row"><td>Income / Credits</td><td>${fmt$(totalIncome)}</td><td>—</td></tr>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Expense Report — ${month}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; background: #f8f9fa; }
    h1 { font-size: 1.8rem; color: #0f3460; border-bottom: 3px solid #e94560; padding-bottom: 8px; }
    h2 { font-size: 1.2rem; color: #16213e; margin-top: 2rem; }
    .meta { color: #888; font-size: .85rem; margin-bottom: 1.5rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,.08); }
    th { background: #0f3460; color: white; padding: 10px 14px; text-align: left; font-size: .85rem; }
    td { padding: 9px 14px; border-bottom: 1px solid #eee; font-size: .9rem; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f0f4ff; }
    .total-row td { font-weight: 700; border-top: 2px solid #0f3460; background: #f0f4ff; }
    .income-row td { color: #2a7a4b; font-style: italic; }
    .badge { display: inline-block; padding: 2px 8px; background: #eef2ff; border-radius: 12px; font-size: .8rem; color: #0f3460; }
    .empty { color: #888; font-style: italic; padding: 1rem 0; }
    .footer { color: #999; font-size: .8rem; margin-top: 2rem; }
  </style>
</head>
<body>
  <h1>Expense Report — ${month}</h1>
  <p class="meta">${txs.length} transactions · Generated ${new Date().toISOString().slice(0, 10)}</p>

  <h2>Spending by Category</h2>
  <table>
    <thead><tr><th>Category</th><th>Amount</th><th>Share</th></tr></thead>
    <tbody>
      ${categoryRows || '<tr><td colspan="3" class="empty">No expenses this month.</td></tr>'}
      <tr class="total-row"><td>Total Expenses</td><td>${fmt$(grandTotal)}</td><td>—</td></tr>
      ${incomeRow}
    </tbody>
  </table>

  <h2>Top 5 Individual Expenses</h2>
  <table>
    <thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Category</th></tr></thead>
    <tbody>
      ${topRows || '<tr><td colspan="4" class="empty">No expenses this month.</td></tr>'}
    </tbody>
  </table>

  <p class="footer">Generated by scripts/expense-report.js · Source: data/expenses.json</p>
</body>
</html>`;
}

// ── Main ─────────────────────────────────────────────────────────────────────

function main() {
  if (!fs.existsSync(DATA_FILE)) {
    console.error(`[report] ERROR: ${DATA_FILE} not found`);
    process.exit(1);
  }

  const data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf-8'));
  const report = buildReport(data, targetMonth);

  fs.mkdirSync(EXPORTS_DIR, { recursive: true });

  const mdPath = path.join(EXPORTS_DIR, `expenses-${targetMonth}.md`);
  const htmlPath = path.join(EXPORTS_DIR, `expenses-${targetMonth}.html`);

  fs.writeFileSync(mdPath, generateMarkdown(report));
  console.log(`[report] ✅ Markdown  → ${mdPath}`);

  fs.writeFileSync(htmlPath, generateHTML(report));
  console.log(`[report] ✅ HTML      → ${htmlPath}`);

  if (!report.txs.length) {
    console.log(`[report]    No transactions found for ${targetMonth}`);
  } else {
    console.log(`[report]    ${report.txs.length} transactions · ${fmt$(report.grandTotal)} total expenses`);
  }
}

main();
