#!/usr/bin/env node
/**
 * export.js — Housing Market Dashboard Exporter
 *
 * Reads data/markets.json and writes:
 *   exports/dashboard.md   — full markdown report
 *   exports/dashboard.html — styled HTML version (open in browser)
 *
 * Usage:
 *   node scripts/export.js
 *   node scripts/export.js --md-only
 *   node scripts/export.js --html-only
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DATA_FILE = path.join(ROOT, "data", "markets.json");
const EXPORTS_DIR = path.join(ROOT, "exports");

const args = process.argv.slice(2);
const MD_ONLY = args.includes("--md-only");
const HTML_ONLY = args.includes("--html-only");

// ─── Helpers ──────────────────────────────────────────────────────────────────
const fmt$ = (n) => n != null ? `$${Math.round(n).toLocaleString()}` : "—";
const fmtPct = (n) => n != null ? `${n.toFixed(2)}%` : "—";
const fmtRate = (r) => r != null ? `${(r * 100).toFixed(2)}%` : "—";
const fmtMin = (c) => c ? `${c.low}–${c.high} min` : "—";
const fmtSchool = (gs, niche) => {
  const parts = [];
  if (gs != null) parts.push(`${gs}/10 GS`);
  if (niche) parts.push(`Niche ${niche}`);
  return parts.length ? parts.join(", ") : "—";
};

function pitiMonthly(price, downPayment, annualRate, termYears, annualTax, annualInsurance = 2400) {
  const loan = price - downPayment;
  const r = annualRate / 12;
  const n = termYears * 12;
  const pi = r === 0 ? loan / n : (loan * r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1);
  return Math.round(pi + annualTax / 12 + annualInsurance / 12);
}

// ─── Markdown Generator ───────────────────────────────────────────────────────
function generateMarkdown(data) {
  const { meta, mortgage_rates, primary_markets, research_markets } = data;
  const { owner_context: oc } = meta;
  const rates = mortgage_rates.rates;
  const down = oc.net_proceeds;
  const rate30 = rates["30yr_fixed"];

  const marketRow = (m) => {
    const piti = pitiMonthly(m.median_price, down, rate30, 30, m.annual_tax);
    const school = fmtSchool(m.school_rating_greatschools, m.school_rating_niche);
    const commute = m.commute_min ? fmtMin(m.commute_min) : (m.dom != null ? `${m.dom}d DOM` : "—");
    return `| **${m.name}** | ${m.state} | ${fmt$(m.median_price)} | ${fmtPct(m.tax_rate_pct)} | ${fmt$(m.annual_tax)}/yr | ${fmt$(piti)}/mo | ${school} | ${commute} |`;
  };

  return `# Housing Market Dashboard
*Last updated: ${meta.last_updated}*

---

## Mortgage Rates (${mortgage_rates.as_of})

| Term | Rate | Notes |
|------|------|-------|
| 30yr fixed | **${fmtRate(rates["30yr_fixed"])}** | ${mortgage_rates.notes ?? ""} |
| 20yr fixed | ${fmtRate(rates["20yr_fixed"])} | |
| 15yr fixed | ${fmtRate(rates["15yr_fixed"])} | |

Rate driver: ${mortgage_rates.rate_driver}

---

## Primary Markets

Assumes **${fmt$(down)} down payment** (net proceeds), 30yr fixed at **${fmtRate(rate30)}**, insurance ~$200/mo.

| Market | State | Median Price | Tax Rate | Ann. Tax | Est. PITI/mo | Schools | Commute |
|--------|-------|-------------|----------|----------|-------------|---------|---------|
${primary_markets.map(marketRow).join("\n")}

---

## Research Markets (Comparison Set)

| Market | State | Median Price | Tax Rate | Ann. Tax | Est. PITI/mo | Schools | Transit |
|--------|-------|-------------|----------|----------|-------------|---------|---------|
${research_markets.map(marketRow).join("\n")}

---

## Affordability Summary (30yr @ ${fmtRate(rate30)}, ${fmt$(down)} down)

${[...primary_markets, ...research_markets]
    .sort((a, b) => pitiMonthly(a.median_price, down, rate30, 30, a.annual_tax) - pitiMonthly(b.median_price, down, rate30, 30, b.annual_tax))
    .map((m, i) => {
      const piti = pitiMonthly(m.median_price, down, rate30, 30, m.annual_tax);
      return `${i + 1}. **${m.name}, ${m.state}** — ${fmt$(piti)}/mo PITI (${fmt$(m.median_price)} price, ${fmt$(m.annual_tax)}/yr tax)`;
    })
    .join("\n")}

---

## Best Schools (ranked by GreatSchools avg)

${[...primary_markets, ...research_markets]
    .filter((m) => m.school_rating_greatschools != null)
    .sort((a, b) => b.school_rating_greatschools - a.school_rating_greatschools)
    .map((m) => `- **${m.name}, ${m.state}** — ${fmtSchool(m.school_rating_greatschools, m.school_rating_niche)}${m.niche_rank ? " · " + m.niche_rank : ""}`)
    .join("\n")}

---

## Fastest Commutes to Midtown

${primary_markets
    .filter((m) => m.commute_min)
    .sort((a, b) => a.commute_min.low - b.commute_min.low)
    .map((m) => `- **${m.name}** (${m.transit}) — ${fmtMin(m.commute_min)} to ${m.transit_terminal}`)
    .join("\n")}

---
*Generated by scripts/export.js · Source data: data/markets.json*
`;
}

// ─── HTML Generator ───────────────────────────────────────────────────────────
function generateHTML(data, markdown) {
  // Simple HTML wrapper — converts markdown tables to HTML manually for clean rendering
  const escaped = markdown
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Housing Market Dashboard — ${data.meta.last_updated}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 1100px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; background: #f8f9fa; }
    h1 { font-size: 1.8rem; color: #0f3460; border-bottom: 3px solid #e94560; padding-bottom: 8px; }
    h2 { font-size: 1.2rem; color: #16213e; margin-top: 2rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,.08); }
    th { background: #0f3460; color: white; padding: 10px 14px; text-align: left; font-size: .85rem; }
    td { padding: 9px 14px; border-bottom: 1px solid #eee; font-size: .9rem; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: #f0f4ff; }
    code { background: #eef; padding: 1px 5px; border-radius: 3px; font-size: .85em; }
    .meta { color: #888; font-size: .8rem; margin-top: 2rem; }
    pre { background: #1a1a2e; color: #eee; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: .85rem; }
  </style>
</head>
<body>
  <h1>🏡 Housing Market Dashboard</h1>
  <p class="meta">Last updated: <strong>${data.meta.last_updated}</strong> · Source: data/markets.json</p>
  <pre>${escaped}</pre>
  <p class="meta">Generated by scripts/export.js</p>
</body>
</html>`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
function main() {
  if (!fs.existsSync(DATA_FILE)) {
    console.error(`[export] ERROR: ${DATA_FILE} not found. Run refresh.js first.`);
    process.exit(1);
  }

  const data = JSON.parse(fs.readFileSync(DATA_FILE, "utf-8"));
  fs.mkdirSync(EXPORTS_DIR, { recursive: true });

  const markdown = generateMarkdown(data);

  if (!HTML_ONLY) {
    const mdPath = path.join(EXPORTS_DIR, "dashboard.md");
    fs.writeFileSync(mdPath, markdown);
    console.log(`[export] ✅ Markdown  → ${mdPath}`);
  }

  if (!MD_ONLY) {
    const html = generateHTML(data, markdown);
    const htmlPath = path.join(EXPORTS_DIR, "dashboard.html");
    fs.writeFileSync(htmlPath, html);
    console.log(`[export] ✅ HTML      → ${htmlPath}`);
  }

  console.log("[export] Done.");
}

main();
